---
- hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  roles:
    - disable-selinux
    - conf-dns
    - conf-ntp
    - { role: common-apt, when: ansible_os_family == 'Debian' }
    - { role: common-yum, when: ansible_os_family == 'RedHat' }
    - postfix-client
